id: I2BBCB222
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T16:01:58+00:00'
last_modified: '2022-06-07T21:17:12.462046+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5194
  title: དར་མོ་བཀའ་རྒྱ་མ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E782:
      image_group_id: I1KG5213
      title: ''
      total_pages: 684
      order: 1
      base_file: E782.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
